### PR TITLE
WIP: Refactor module structure

### PR DESCRIPTION
**Pull request by CraigFe**
A very WIP attempt at splitting the internal module structure, with a view to simplifying the API.

### CODE REVIEW

**Comment by hannesm** [comment]
I use this library, and am curious what the motivation for this is? you mention "simplify API" - but I'm not able to find what are the API "simplifications" in this PR - apart from splitting metrics.mli into various modules (which is mainly a stylistic question imho).

**Comment by CraigFe** [comment]
Agreed that it's just module splitting so far. I find the internal structure of `metrics.mli` quite hard to piece apart, so splitting it out seems like a worthy goal to me, but opinions may vary :)

Perhaps "simplifying" is the wrong word. I'm looking to write a couple of MWEs, and as part of that do a pass over the docs / internal structure to try to make the library a bit simpler to understand. Afaik, the interface itself is simple enough; I don't see a motivation for breaking changes.

**Comment by hannesm** [comment]
> I find the internal structure of `metrics.mli` quite hard to piece apart

At least for me, similar to `logs`, its pretty nice to have a single module with all the core functionality.

> I don't see a motivation for breaking changes

And then you change the interface in a way that users need to change their code? Maybe I misunderstand what you mean with "breaking changes" (see https://github.com/mirage/metrics/pull/30/files#diff-7bf502183f7de382f66e7eff2237e12e). I'm rather sceptical of the advantages of this PR as is.

I agree that more documentation could be added, and feature-wise in my opinion `metrics` is not yet complete.

**Comment by CraigFe** [comment]
> And then you change the interface in a way that users need to change their code? Maybe I misunderstand what you mean with "breaking changes" (see https://github.com/mirage/metrics/pull/30/files#diff-7bf502183f7de382f66e7eff2237e12e). I'm rather sceptical of the advantages of this PR as is.

You're right to be skeptical, as the PR is still WIP. I'm aware that `metrics.mli` currently contains breaking changes (particularly pushing the field type witnesses into the `Field` module), but it's all temporary as I get to grips with the library.

**Comment by samoht** [comment]
Hi @CraigFe, thanks for the PR!

I think I am not totally convinced by splitting everything into various files :-) And it would be easier to review the API / documentation changes if you just keep the existing organisation.

But yes, I agree that the current internals of metrics are quite complex at the moment and any effort to simplify the dependencies is very welcome

**Comment by CraigFe** [comment]
Thanks both for the feedback. Closing to open a less invasive PR elsewhere.

**Pull request closed without merging**
